### PR TITLE
dice throw problem in dp

### PR DESCRIPTION
**Pull request by AK16092003**

### CODE REVIEW

**Comment by HARSH-nith** [comment]
recheck the code please

**Comment by HARSH-nith** [comment]
write complete code,  and make it compatible with running on the local system (include files like output.txt and input .txt)

**Comment by AK16092003** [comment]
@HARSH-nith 
Updates done

**Comment by HARSH-nith** [comment]
@AK16092003 buddy your code is not working check it

**Comment by AK16092003** [comment]
may i know the input and output formats ?

**Comment by AK16092003** [comment]
image

works perfectly fine for me!

**Pull request merged**
